#!/bin/bash
declare rd=$'\033[31m'      #red
declare rt=$'\033[0m'       #reset                                              
declare bd=$'\033[1m'       #bold 
declare yw=$'\033[33m'      #yellow                                             
declare current_branch="$(git branch --show-current)"

if [ "$current_branch" = "master" -o "$current_branch" = "main" ]; then
  read -p "${yw}Warning:$rt You're about to commit to ${bd}${rd}${current_branch}$rt, is that what you intended? [y|n] 
  " -n 1 -r < /dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
    exit 0 # commit will execute
  fi
  exit 1 # commit will not execute
else
  exit 0 # commit will execute
fi
