#!/bin/bash
## Setup for usbip client service
#Ubuntu:
#sudo apt-get install linux-tools-generic hwdata usbutils -y
#Debian:
#sudo apt-get install usbip hwdata usbutils -y
#Fedora:
#sudo dnf install usbip hwdata usbutils -y

_checkCommand() { command -v "$@" &>/dev/null; }
_checkCommand usbip || { echo "Warning: Remember to install the usbip packages first"; exit 1; }

modprobe vhci-hcd
sh -c 'printf "%s\n" "vhci-hcd" >> /etc/modules'
cp "$PWD/usbip.service" /lib/systemd/system/usbip.service
curl -LJ https://raw.githubusercontent.com/SimonWoodtli/dotfiles/main/scripts/usbipclient -o /usr/sbin/usbipclient
chmod +x /usr/sbin/usbipclient
systemctl --system daemon-reload
systemctl enable usbip.service --now
