#!/bin/sh
## dependencies: dotool, wofi, xclip
## 1. run setup script or copy the scripts you want to : /bin
## 2. create a custom keyboard shortcut: use __bmw-gui as the command
## TODO use dotool to create a Enter keystroke after filling out the url
declare selectBookmark="$(sed '/^#.*#$/d' "$HOME/Private/bookmarks/bookmarksCrypto" | grep -v '^#' | wofi -d 2>/dev/null | cut -d' ' -f1 )"
## copy selected bookmark to your x11 clipboard
echo "$selectBookmark" | tr -d '\n' | xclip -sel clipboard
## write out the selected bookmark into the currently active window
## useful in a GUI Browser to write into your address bar
echo "type "$selectBookmark"" | dotool
