#!/bin/sh
## Author: rwxrob

if ! type browser-sync >/dev/null 2>&1; then
  ##FIXME telln requires tell which I don't have
  #telln '*Need to install `browser-sync`*.'
  echo 'Need to install browser-sync.'
  exit 1
fi

browser-sync start \
  --no-notify --no-ui \
  --ignore '**/.*' \
  -sw

#browser-sync start --server --files "*.html, css/*.css"'
