#!/bin/sh
## create variable for your system
spruce_type=linux
OS=$(uname)
## get correct link with jq
URL=$(curl -s https://api.github.com/repos/ventoy/Ventoy/releases/latest | jq -r ".assets[] | select(.name | test(\"${spruce_type}\")) | .browser_download_url")
TARBALL=${URL##*/}
NAME=${TARBALL%-*}
## colors
red=$'\033[31m'
black=$'\033[30m'
green=$'\033[32m'
yellow=$'\033[33m'
blue=$'\033[34m'
magenta=$'\033[35m'
cyan=$'\033[36m'
white=$'\033[37m'
reset=$'\033[0m'
bold=$'\033[1m'

if [ $OS != 'Linux' ] ; then
  echo "${red}Error:$reset ${bold}Sorry designed to be installed on Linux only.$reset"
  exit 1
fi

echo "$cyan
██╗   ██╗███████╗███╗   ██╗████████╗ ██████╗ ██╗   ██╗
██║   ██║██╔════╝████╗  ██║╚══██╔══╝██╔═══██╗╚██╗ ██╔╝
██║   ██║█████╗  ██╔██╗ ██║   ██║   ██║   ██║ ╚████╔╝
╚██╗ ██╔╝██╔══╝  ██║╚██╗██║   ██║   ██║   ██║  ╚██╔╝
 ╚████╔╝ ███████╗██║ ╚████║   ██║   ╚██████╔╝   ██║
  ╚═══╝  ╚══════╝╚═╝  ╚═══╝   ╚═╝    ╚═════╝    ╚═╝
$reset"

## download tarball
curl -LJ -o /tmp/$TARBALL $URL

## extract tarball
tar -xvzf /tmp/$TARBALL -C /tmp
echo ${green}Done:$reset Extracted Ventoy successfully.
echo "${blue}Hint 1:$reset cd into ${bold}/tmp/${NAME}$reset"
echo "${blue}Hint 2:$reset Figure out which device to format with Ventoy.  Run ${bold}\`lsblk\`$reset"
echo "${blue}Hint 3:$reset Install Ventoy on your device with
${bold}\`sudo sh Ventoy2Disk.sh [-i | -I | -u] /dev/XXX\`$reset

    -i   install ventoy to sdX (fail if disk already installed with ventoy)
    -I   force install ventoy to sdX (no matter installed or not)
    -u   update ventoy in sdX"
