#!/bin/bash
## Author: Simon D. Woodtli
## Hotkeys: Return, 1, 2
## Note: When thumbmail mode starts up with 'Return' it needs an
## initial  j/k or some regular ~/.config/feh/key mapped keystroke
## to start listening to hotkey strokes
declare fehpath=/usr/bin/feh
[ ! -x $fehpath ] && fehpath=/usr/local/bin/feh
declare key="$2"
declare imagePath="$1"
declare buffer=/tmp/feh-buffer
declare strBuffer

case "$key" in
  Return) ## toggle thumbnail mode:
    ## Minor glitches:
    ## 1. going from thumbnail mode then render image with "l" breaks
    ## 2. if quitting feh from thumbnail mode with "q" breaks
    ## Solution hit enter again
    kill -9 "$(pidof feh)"
    strBuffer="$(< "$buffer")"
    if [[ "$strBuffer" == "window" ]] || [[ ! -f "$buffer" ]]; then
      printf "%s\n" "thumbnail" > "$buffer"
      exec feh --scale-down --auto-zoom -F -t -E 150 -y 150 -W 1920 
      #FIXME if quit out of thumbnail mode write window to buffer (reset)
    else
      printf "%s\n" "window" > "$buffer"
      exec feh
      #FIXME if switching from thumbnail to render image write window to buffer (reset)
    fi;;
  1) ##FIXME xclip copies png/jpeg but not webp
    xclip -selection clipboard -t "$(file --mime-type -b "$imagePath")" -i "$imagePath";;
  2) ## set dark theme wallpaper:
    gsettings set org.gnome.desktop.background picture-uri-dark file://"$imagePath"
    ## set light theme wallpaper:
    gsettings set org.gnome.desktop.background picture-uri file://"$imagePath" ;;
esac
# 3) ##TEST HOTKEY:
#    [ ! -f "$buffer" ] && echo buffer does not exist || echo buffer exists;;
