#!/usr/bin/python
#make sure you have whisper installed: https://github.com/openai/whisper
import whisper
import sys
model = whisper.load_model("base")
audio = sys.argv[1]
transcribe = model.transcribe(audio)
#translate = model.transcribe(audio, task="translate")
print(transcribe["text"])
#print(translate["text"])
