#!/bin/bash
## difference between $* and $@? Both hold list of all arguments passed to
## script. However the values are not the same if surrounded by double quotes:
## - $@ expanded as "$1" "$2" "$3" ... "$n"
## - $* expanded as "$1y$2y$3y...$n", where y is the value of IFS variable i.e. 
##  "$*" is one long string and $IFS act as an separator or token delimiters.
# IFS=+
# echo $*
# echo "$*"
# echo
# echo $@
# echo "$@"
# exit

[[ "$1" == -h || "$1" == --help || "$1" == :help ]] && curl -sS https://cht.sh/:help | bat && exit
[ "$1" == :list ] && curl -sS https://cht.sh/:list | bat && exit
[ "$1" == :intro ] && curl -sS https://cht.sh/:intro | bat && exit

cheat() {
  language="$1"
  if [ $# -ge 1 ]; then
    shift
  fi
  IFS=+; curl -sS https://cht.sh/$language/"$*"
}

cheat "$@"
