#!/bin/bash
## Author: Simon D. Woodtli
## feh wrapper script
declare fehpath=/usr/bin/feh
declare keyhandler=__feh-keyhandler
declare rd=$'\033[31m'
declare rt=$'\033[0m'
[ ! -x $fehpath ] && fehpath=/usr/local/bin/feh

_have() { type "$1" >/dev/null; }
_checkDependency() {
  _have feh || { echo "${rd}ERROR:$rt Install feh first"; exit 1; }
}
_countImg() {
  ##TODO test: are these image types all supported by feh?
  local -i countImg=$(find . \
    -maxdepth 1 -type f \
    \( -name "*.png" \
    -o -name "*.jpeg*" \
    -o -name "*.jpg" \
    -o -name "*.jp2" \
    -o -name "*.tif*" \
    -o -name "*.bmp" \
    -o -name "*.svg" \
    -o -name "*.gif" \
    -o -name "*.apng" \
    -o -name "*.webm" \
    -o -name "*.heic" \
    -o -name "*.avif" \
    -o -name "*.webp" \) | wc -l)
  printf "%s\n" "$countImg"
}
_feh() {
  local -i countImg=$(_countImg)
  local -a cmd=(
    "$fehpath" "--scale-down" "--auto-zoom" "-F"
    "--action" ";$keyhandler $PWD/%F Return"
    "--action2" ";$keyhandler $PWD/%F 2"
  )
  _have xclip && cmd+=( "--action1" ";$keyhandler $PWD/%F 1" )
  if (( countImg > 1 )); then
    cmd+=( "--start-at" )
    exec "${cmd[@]}" "$@" 2>/dev/null
  else
    exec "${cmd[@]}"
  fi
}
_checkDependency && _feh "$@"
