#!/bin/sh
exec feh --scale-down --auto-zoom -F -t -E 150 -y 150 -W 1920
## Now I need the feh-wrapper to know which script to execute and it is
## only defined for action0 which allows Return to activate thumbnail.
## If I wanted another keybinding like action1 = 1 to execute another
## script. I would need to create another script in $SCRIPTS.

## TODO 1 feat: How to have all commands: Return + [1-9] execute the same script
## (feh-keyhandler) but each one different code within.
## -> case/switch would probably be needed
##
## easy part: the feh-wrapper would need: --action[1-9] ";$SCRIPTS/feh-keyhandler $PWD/%F"
## tricky: how to read which keystroke happened and according to this
## keystroke execute a certain line of code (switch/case).


## arch-wiki: how sxiv handles keystrokes, maybe feh can do something
## similar?

# #!/bin/sh
# while read file
# do
# case "$1" in
# "C-d")
# mv "$file" ~/.trash ;;
# "C-r")
# convert -rotate 90 "$file" "$file" ;;
# "C-c")
# echo -n "$file" | xclip -selection clipboard ;;
# "C-w")
# nitrogen --save --set-zoom-fill "$file" ;;
# esac
# done

##TODO 2 fix: activate thumbnail -> toggle thumbnail mode
## right now my script just opens a thumbnail window when `Return/:` but
## if entered multiple times it keeps opening new thumbnail windows.
## It should be activate/deactivate -> toggle
