#!/bin/bash
## Author: Simon D. Woodtli
gck() {
  if [ "$#" -eq 1 ]; then
    branches=($(git branch | cut -c 3-))
    for branch in "${branches[@]}"; do
      if [[ "${branch}" = $1 ]]; then
        git checkout $1
        echo "Switched to an existing branch: ${branch}"
        return 0
      fi
    done
    echo "Created and switched to a new branch: $1"
    git checkout -b $1
  else
    echo "Please provide a single argument: gck \$1"
  fi
}

gck "$1"
