#!/bin/sh
## Author: Simon D. Woodtli
[ -z "$1" ] && echo "Needs a pdf file or a DOI as an argument." && return 1

if [ -f "$1" ]; then
	doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
	#grep -oP "\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\"&\'<>])\S)+)\b" | head -n 1)
	doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1) ||
	echo "Could not find a DOI reference in the pdf file"
	[ -z "$doi" ] && return 2
else
	doi="$1"
fi

# Curl info from crossref.org for the bib citation
curl -s "https://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n"
