#!/usr/bin/python3
import sys
import json
import yaml
print(yaml.dump(json.load(open(sys.argv[1]))))
#print yaml.dump(yaml.load(json.dumps(json.loads(open(sys.argv[1]).read()))), default_flow_style=False)


