#!/bin/bash
## Author: Simon D. Woodtli
#TODO rewrite to choose using Virtualbox, Vmware or Qemu/Virtmanager
startVM() {
  ## Start Whonix-Gateway headless
  vboxmanage startvm --type headless Whonix-Gateway-CLI
  sleep 10
  ## Start Kali
  vboxmanage startvm Kali
}
poweroffVM() {
  ## Poweroff Kali
  vboxmanage controlvm Kali poweroff
  sleep 2
  ## Poweroff Whonix-Gateway
  vboxmanage controlvm Whonix-Gateway-CLI poweroff
}

## TODO make one script for all VMs
## TODO
## * fix error msg when multiple parameters given or `whonix 2 s`
## * Make echo msg in different color
if [ -z "$@" ]; then
  startVM
elif [ "$1" == "off" ]; then
  poweroffVM
else
  echo 'The only valid commands are: to start VMs: `whonix` to poweroff VMs: `whonix off`'
  exit 1
fi
