#!/usr/bin/bash
## useful if you found a link when browsing in lynx and want to add it to a zet
## use in vim with !!lynxa to get bookmarks

count=1
if test -n "$1"; then
    count="$1"
fi

IFS=$'\n'
html=($(tail -"${count}" ~/.lynx_bookmarks.html | pandoc -f html -t markdown --wrap=none))

for line in ${html[@]}; do
   [[ $line =~ ^\[(.+)\]\((.+)\) ]]
   echo "* ${BASH_REMATCH[1]}  "
   echo "  <${BASH_REMATCH[2]}>"
done
