#!/bin/sh
## Author: rwxrob
from=$(lastpic)
to="$PWD/$1"
mv "$from" "$to"
##FIXME telln requires tell which I don't have
#telln "*From:* ***$from***\n*To:   **$to**"
echo "*From:* ***$from***\n*To:   **$to**"
