#!/bin/bash
## Author: Simon D. Woodtli
## thanks to rwxrob for this idea
## TODO redo whole script
## make printed line include my basic header with Author etc.

test ! -n "${SCRIPTS}"  && echo "SCRIPTS not set" && exit 1;
test ! -n "${1}"  && echo "usage: newscript <name>" && exit 1;

path="${SCRIPTS}/${1}"

if [ -e "${path}" ]; then
  read -p "${1} already exists. Edit? " yes
  case "${yes}" in
    y|yes|yep|yeppers|yeah|ok|okay) exec vim "${path}"
  esac
  exit 0
fi

printf "#!/bin/bash\n\n" > "${path}"
chmod +x "${path}" 
exec vim +2 "${path}"
