#!/bin/sh
## Author: rwxrob

if ! type pv >/dev/null 2>&1; then
  ##FIXME telln requires tell which I don't have
  #telln 'Missing `pv` command.'
  echo 'Missing `pv` command.'
  exit 1
fi

yes | pv |ssh "$1" "cat >/dev/null"
