#!/usr/bin/python
## Author: Simon D. Woodtli

## to use: tsv2csv < input.tsv > output.csv
## works with embedded commas as well!
import sys
import csv

tabin = csv.reader(sys.stdin, dialect=csv.excel_tab)
commaout = csv.writer(sys.stdout, dialect=csv.excel)
for row in tabin:
  commaout.writerow(row)

