#!/bin/bash
declare w3mpath=/usr/bin/w3m
[[ ! -x "$w3mpath" ]] && w3mpath=/usr/local/bin/w3m

if [ ! -x "$w3mpath" ]; then
  echo "Doesn't look like w3m is installed."
  exit 1
fi

# create three panes and run w3m in middle
#if [[ $(tmux list-panes | wc -l) -lt 2 ]]; then
  #tmux split-window -h -l 90%
  #tmux swap-pane -s 1 -t 2; tmux select-pane -t 2 #starts w3m in middle pane
#fi

width=$(tput cols)
stty cols 87
eval "$w3mpath" "$@" && stty cols $width
