#!/bin/sh
## set wallpaper for Gnome Desktops
## set dark theme:
gsettings set org.gnome.desktop.background picture-uri-dark file://"$PWD/${1%/*}"
## set light theme:
gsettings set org.gnome.desktop.background picture-uri file://"$PWD/${1%/*}"
## if on window managers use feh
