#!/usr/bin/sh
##search all window and jump
# tmux list-windows formating
target_spec="#{session_name}:#{window_id}:"
list_data="#{window_name} #{pane_title} #{pane_current_path} #{pane_current_command}"

__fzf_cmd() {
  fzf -e -i --prompt="Select a window: " --info=default --layout=reverse --tiebreak=index
}

# select window
line="$(tmux list-windows -a -F "$target_spec $list_data" | __fzf_cmd)" || exit 0
session="$(echo "$line" |  cut -d ':' -f1)"
window_num="$(echo "$line" |  cut -d ':' -f2)"

tmux select-window -t "$window_num" && tmux switch-client -t "$session"
