#!/usr/bin/sh
##search all panes and jump to selected
declare target_spec="#{session_name}:#{window_id}:#{pane_id}:"
declare list_data="#{window_name} #{pane_title} #{pane_current_path} #{pane_current_command}"

__fzf_cmd() {
  fzf -e -i --prompt="Select a pane: " --info=default --layout=reverse --tiebreak=index
}

# select pane
declare line="$(tmux list-panes -a -F "$target_spec $list_data" | __fzf_cmd)" || exit 0
declare session="$(echo "$line" |  cut -d ':' -f1)"
declare window_num="$(echo "$line" |  cut -d ':' -f2)"
declare pane_num="$(echo "$line" |  cut -d ':' -f3)"

tmux select-pane -t "$pane_num" && tmux select-window -t "$window_num" && tmux switch-client -t "$session"
