#!/usr/bin/sh
##create 'communication' session and jump to first window                          
##or if session exists just jump to first window                                   
session="communication"
tmux has-session -t $session 2>/dev/null
## create tmux session if it doesn't already exist
if [ "$?" ]; then
  tmux new-session -d -s "$session" -c "$HOME"
  ## create windows:
  tmux send-keys -t "$session":1 'weechat' C-m

  tmux new-window -t "$session":2 -c "$HOME"
  tmux send-keys -t "$session":2 'neomutt' C-m
  #tmux new-window -t "$session":3 -n 'im' -c "$HOME"
  #tmux send-keys -t "$session":3 'finch' C-m
fi
## jump to first window in "communication" session
tmux switch-client -t "$session":1
