#!/usr/bin/sh
## jump to "weechat" window in "communication" session
window="weechat"
session="communication"
filterSession="$(tmux list-windows -a -F "#S:#I-#W" | grep "$window" | grep "$session" | cut -d "-" -f 1)"
tmux switch-client -t "$filterSession"
