#!/usr/bin/sh
## jump to "w3m" window in "research" session
declare window="w3m"
declare session="research"
declare filterSession="$(tmux list-windows -a -F "#S:#I-#W" | grep "$window" | grep "$session" | cut -d "-" -f 1)"
tmux switch-client -t "$filterSession"
